acme_store_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeStoreBundle:Default:index }
acme_store_create:
    pattern:  /create
    defaults: { _controller: AcmeStoreBundle:Default:create }