homepage:
    pattern: /
    defaults: { _controller: TaoBlogBundle:Page:index }
tao_blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: TaoBlogBundle:Default:index }
about:
    pattern: /about
    defaults: { _controller: TaoBlogBundle:Page:about }
contact:
    pattern: /contact
    defaults: { _controller: TaoBlogBundle:Page:contact }
show:
    pattern: /{id}
    defaults: { _controller: TaoBlogBundle:Page:show }
    requirements:
      _method: GET
      id: \d+